import { auth, db, storage } from "./firebase-app.js";
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, setDoc, Timestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { getDownloadURL, ref, uploadBytes } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-storage.js";

const $ = id => document.getElementById(id);
const state = { posts: [], currentId: null, dirty: false };
const today = () => new Date().toISOString().slice(0,10);
const slugify = s => String(s).normalize('NFKC').toLowerCase().trim().replace(/[^\p{L}\p{N}\s-]/gu, '').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,100) || `post-${Date.now()}`;
const safe = html => window.DOMPurify ? DOMPurify.sanitize(html, {ALLOWED_TAGS:['p','br','strong','em','u','s','h2','h3','h4','ul','ol','li','blockquote','a','img','hr'],ALLOWED_ATTR:['href','target','rel','src','alt','loading']}) : '';
const toast = (msg, error=false) => { const el=$('toast'); el.textContent=msg; el.style.background=error?'#991b1b':'#0f172a'; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),3000); };
function show(view){ ['loginView','deniedView','appView'].forEach(id=>$(id).classList.add('hidden')); $(view).classList.remove('hidden'); }
function setError(msg=''){ $('editorError').textContent=msg; }
function updateCounters(){ $('excerptCounter').textContent=`${$('excerpt').value.length}/220`; const text=$('contentEditor').innerText.trim(); $('contentCounter').textContent=`${text?text.split(/\s+/).length:0} words`; }
function resetEditor(){ state.currentId=null; state.dirty=false; $('postForm').reset(); $('slug').dataset.edited=''; $('postId').value=''; $('publishDate').value=today(); $('readTime').value='5 min read'; $('contentEditor').innerHTML=''; $('imageUrl').value=''; $('coverPreview').innerHTML='<span><i class="fas fa-image"></i> Cover preview</span>'; $('editorHeading').textContent='Create article'; $('saveState').textContent='New article'; setError(''); updateCounters(); document.querySelectorAll('.post-item').forEach(x=>x.classList.remove('active')); }
function fillEditor(p){ state.currentId=p.id; state.dirty=false; $('postId').value=p.id; $('title').value=p.title||''; $('slug').value=p.slug||p.id; $('category').value=p.category||'General Health'; $('readTime').value=p.readTime||'5 min read'; $('publishDate').value=p.publishDate||toDateInput(p.publishedAt||p.date); $('excerpt').value=(p.excerpt && !/^A concise description shown on the blog card and useful for search previews\.?$/i.test(p.excerpt.trim())) ? p.excerpt : ''; $('imageUrl').value=p.image||''; $('contentEditor').innerHTML=safe(p.content||''); $('seoTitle').value=p.seoTitle||''; $('seoDescription').value=p.seoDescription||''; $('published').checked=!!p.published; setCover(p.image); $('slug').dataset.edited='1'; $('editorHeading').textContent='Edit article'; $('saveState').textContent=`Last saved ${formatDate(p.updatedAt)}`; setError(''); updateCounters(); renderPosts(); }
function toDateInput(v){ const d=v?.toDate?v.toDate():new Date(v||Date.now()); return Number.isNaN(d.getTime())?today():d.toISOString().slice(0,10); }
function formatDate(v){ if(!v)return 'recently'; const d=v?.toDate?v.toDate():new Date(v); return Number.isNaN(d.getTime())?'recently':d.toLocaleDateString(); }
function setCover(url){ $('coverPreview').innerHTML=''; if(url){const img=document.createElement('img');img.src=url;img.alt='Cover preview';img.onerror=()=>{$('coverPreview').innerHTML='<span>Image could not be loaded</span>';};$('coverPreview').appendChild(img)}else $('coverPreview').innerHTML='<span><i class="fas fa-image"></i> Cover preview</span>'; }
function collectForm(){ const title=$('title').value.trim(); return { title, slug:slugify($('slug').value.trim()||title), category:$('category').value, readTime:$('readTime').value, publishDate:$('publishDate').value, excerpt:$('excerpt').value.trim(), image:$('imageUrl').value.trim(), content:safe($('contentEditor').innerHTML.trim()), seoTitle:$('seoTitle').value.trim(), seoDescription:$('seoDescription').value.trim(), published:$('published').checked }; }
function validate(p){ if(!p.title) return 'Title is required.'; if(!p.slug) return 'Slug is required.'; if(!p.excerpt) return 'Please write a short excerpt.'; if(!p.content || p.content==='<br>') return 'Article content is required.'; if(p.image && !/^https:\/\//i.test(p.image)) return 'Cover image URL must start with https:// or use an uploaded image.'; return ''; }
async function uploadCoverIfNeeded(slug){ const file=$('imageFile').files?.[0]; if(!file)return $('imageUrl').value.trim(); if(file.size>5*1024*1024)throw new Error('Image is larger than 5 MB.'); if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))throw new Error('Only JPG, PNG, WebP, or AVIF images are allowed.'); const path=`blog-images/${auth.currentUser.uid}/${slug}-${Date.now()}`; const snap=await uploadBytes(ref(storage,path),file,{contentType:file.type,cacheControl:'public,max-age=31536000'}); const url=await getDownloadURL(snap.ref); $('imageUrl').value=url; setCover(url); $('imageFile').value=''; return url; }
async function savePost(forcePublished){ setError(''); const p=collectForm(); p.published=forcePublished; $('published').checked=forcePublished; const err=validate(p); if(err){setError(err);return;} const btn=forcePublished?$('publishBtn'):$('saveDraftBtn'); const old=btn.innerHTML; btn.disabled=true; btn.innerHTML='<i class="fas fa-spinner fa-spin"></i> Saving…'; try{ p.image=await uploadCoverIfNeeded(p.slug); const id=state.currentId||p.slug; const refDoc=doc(db,'blogs',id); const existing=state.currentId?state.posts.find(x=>x.id===state.currentId):null; const dateValue=Timestamp.fromDate(new Date(`${p.publishDate}T12:00:00`)); const data={...p,publishedAt:dateValue,updatedAt:serverTimestamp(),...(existing?{}:{createdAt:serverTimestamp()})}; await setDoc(refDoc,data,{merge:true}); state.currentId=id; state.dirty=false; toast(p.published?'Article published.':'Draft saved.'); await loadPosts(); const saved=state.posts.find(x=>x.id===id); if(saved)fillEditor(saved); }catch(e){console.error(e);setError(e.message||'Could not save the article.');toast('Save failed.',true);}finally{btn.disabled=false;btn.innerHTML=old;} }
async function loadPosts(){ const snap=await getDocs(query(collection(db,'blogs'),orderBy('updatedAt','desc'),limit(200))); state.posts=snap.docs.map(d=>({id:d.id,...d.data()})); renderPosts(); updateStats(); }
function renderPosts(){ const list=$('postList'); const q=$('postSearch').value.trim().toLowerCase(); const arr=state.posts.filter(p=>`${p.title||''} ${p.category||''}`.toLowerCase().includes(q)); if(!arr.length){list.innerHTML='<div class="empty-list">No articles found.</div>';return;} list.innerHTML=''; arr.forEach(p=>{const el=document.createElement('div');el.className=`post-item ${p.id===state.currentId?'active':''}`;el.innerHTML=`<h3></h3><div class="post-meta"><span>${p.category||'General'}</span><span class="badge ${p.published?'published':'draft'}">${p.published?'Published':'Draft'}</span></div>`;el.querySelector('h3').textContent=p.title||'Untitled';el.onclick=()=>fillEditor(p);list.appendChild(el);});}
function updateStats(){ $('statTotal').textContent=state.posts.length; $('statPublished').textContent=state.posts.filter(p=>p.published).length; $('statDrafts').textContent=state.posts.filter(p=>!p.published).length; $('statCategories').textContent=new Set(state.posts.map(p=>p.category).filter(Boolean)).size; }
async function deleteCurrent(){ if(!state.currentId)return; const p=state.posts.find(x=>x.id===state.currentId); if(!p)return; if(!confirm(`Delete “${p.title}”? This cannot be undone.`))return; try{await deleteDoc(doc(db,'blogs',state.currentId));toast('Article deleted.');resetEditor();await loadPosts();}catch(e){console.error(e);toast('Delete failed.',true);} }
function preview(){ const p=collectForm(); $('previewContent').innerHTML=`<article class="preview-article"><h1>${escapeHtml(p.title)}</h1><div class="meta">${escapeHtml(p.category)} · ${escapeHtml(p.readTime)} · ${escapeHtml(p.publishDate)}</div>${p.image?`<img src="${escapeAttr(p.image)}" alt="">`:''}<p><strong>${escapeHtml(p.excerpt)}</strong></p><div>${safe(p.content)}</div></article>`; $('previewModal').classList.remove('hidden'); }
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const escapeAttr=escapeHtml;
async function importLegacy(){ if(!window.legacyBlogsData?.length){toast('No legacy data file found.',true);return;} if(!confirm(`Import ${window.legacyBlogsData.length} existing articles into Firebase? Existing IDs will be updated.`))return; let n=0; try{for(const p of window.legacyBlogsData){const date=new Date(p.date);await setDoc(doc(db,'blogs',p.id),{...p,slug:p.id,published:true,publishedAt:Timestamp.fromDate(date),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),seoTitle:p.title,seoDescription:p.excerpt},{merge:true});n++;}toast(`${n} legacy articles imported.`);await loadPosts();}catch(e){console.error(e);toast('Import failed.',true);} }
function setupEditor(){ $('title').addEventListener('input',()=>{if(!$('slug').dataset.edited)$('slug').value=slugify($('title').value)});$('slug').addEventListener('input',()=>{$('slug').dataset.edited='1'});$('excerpt').addEventListener('input',updateCounters);$('contentEditor').addEventListener('input',()=>{state.dirty=true;updateCounters()});$('imageUrl').addEventListener('input',()=>setCover($('imageUrl').value.trim()));document.querySelectorAll('#toolbar button[data-cmd]').forEach(b=>b.addEventListener('click',()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);$('contentEditor').focus();updateCounters();}));$('quoteBtn').onclick=()=>{document.execCommand('formatBlock',false,'blockquote');$('contentEditor').focus()};$('linkBtn').onclick=()=>{const url=prompt('Secure link URL (https://…)');if(url&&/^https:\/\//i.test(url))document.execCommand('createLink',false,url);$('contentEditor').focus()};$('clearBtn').onclick=()=>{document.execCommand('removeFormat');$('contentEditor').focus()};$('newPostBtn').onclick=resetEditor;$('saveDraftBtn').onclick=()=>savePost(false);$('publishBtn').onclick=()=>savePost(true);$('previewBtn').onclick=preview;$('closePreview').onclick=()=>$('previewModal').classList.add('hidden');$('postSearch').addEventListener('input',renderPosts);$('logoutBtn').onclick=()=>signOut(auth);$('deniedLogout').onclick=()=>signOut(auth);$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value)}catch(err){console.error(err);$('loginError').textContent='Invalid email/password or sign-in is disabled.';}};$('imageFile').addEventListener('change',()=>{const f=$('imageFile').files?.[0];if(f){$('coverPreview').innerHTML='';const img=document.createElement('img');img.src=URL.createObjectURL(f);$('coverPreview').appendChild(img)}});$('postForm').addEventListener('input',()=>state.dirty=true);$('deleteBtn').onclick=deleteCurrent;$('importBtn').onclick=importLegacy;window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});}
async function bootUser(user){ if(!user){show('loginView');return;} $('adminEmail').textContent=user.email||''; const adminSnap=await getDoc(doc(db,'admins',user.uid)); if(!adminSnap.exists()||adminSnap.data().active===false){show('deniedView');return;} show('appView'); resetEditor(); await loadPosts(); }
setupEditor();
onAuthStateChanged(auth,user=>bootUser(user).catch(e=>{console.error(e);toast('Could not load admin account.',true);}));
